### ISSUE TITLE
Unknown date?

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#14] opened 2016-11-23 15:55 UTC
I'm getting this error: `{ type: 'unknown_date',  entry: 'bentley_academic_2011',  field_name: 'date' }` when I parse the reference below. I think the `field_name` should probably be `year` rather than `date`, and the format in this field is sometimes used as the origdate. Again, not saying it's nice, but this is what people give me, and keeping in mind Postel's law... 

EDIT: same goes for another entry that has `year = {1875 [2004]}`

```
@article{bentley_academic_2011,
  abstract = {State planning has been a defining means for modern subjects to regulate the passage of time. In practice, it is the focus of multiple conflicts and doubts, which planners attempt to mediate. In this paper, I address the regimes of time that planning both promotes and encounters, and tease out what these imply for anthropology. Using ethnography of Norwegian and Swedish planning offices and their encounters with participatory planning, I question recent claims that there has been an evacuation of the near future or a retreat of administrative intervention. I also suggest that recent anthropological concerns with time have been confined by their attempts to characterize the changing timescapes of specific modal shifts, such as from the modern to the neoliberal. Instead, in my ethnography, I focus not on tracking epochal breaks in time, but on demonstrating how time is manipulated, and how multiple temporalities are performed in ongoing projects of democratic planning.},
  annotation = {This is the child note},
  author = {Abram, Simone},
  doi = {10.1111/1467-9655.12097},
  issn = {1467-9655},
  journaltitle = {Journal of the Royal Anthropological Institute},
  keywords = {måske},
  langid = {english},
  pages = {129--147},
  rights = {© Royal Anthropological Institute 2014},
  shortjournal = {J R Anthropol Inst},
  shorttitle = {6~{{The}} Time It Takes},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {6~{{The}} Time It Takes: Temporalities of Planning},
  url = {http://onlinelibrary.wiley.com.ep.fjernadgang.kb.dk/doi/10.1111/1467-9655.12097/abstract},
  urldate = {2014-12-27},
  volume = {20},
  xref = {welker_andreas_1999},
  year = {[2014]}
}
```

**Comment by retorquere** [comment] 2016-11-23 15:56
Could in the case of `unknown_date` the date value be put in the error? It'd make my work a lot easier.

**Comment by johanneswilm** [comment] 2016-11-23 17:23
I've added the value info. The reason it mentions the date field is that it first attempts to move year, month, day field to the date field and then sees if it can interpret it.

15 years ago I wrote my first bibtex files that same way, so I can see how people can get the idea that this is how to do it. I'm ok with accepting more possible date formats, but we should write something like a simple spec for everything we accept, if there isn't something like that already somewhere.

**Comment by retorquere** [comment] 2016-11-23 18:14
wrt moving the fields, this makes it harder for me to diagnose when I get an error; right now it claims that there's an error in the `date` field for `year = {[1990] 2002}`, as it is neither an error according to the biblatex spec but it's also not in the `date` field. I'm not aiming to be pedantic about it, but in this case I have test cases (which in my case means issue reports from the field) that rely on this behavior.

What you say is all true, but the fact of the matter is that I still regularly get files that (ab)use the `year` field -- as long as it's still supported by biblatex (and it is), this is bound to stay for still some time.

**Comment by johanneswilm** [comment] 2016-11-24 08:47
the error should now name the original field

**Comment by retorquere** [comment] 2016-11-24 08:55
Super, that makes testing a whole lot easier. It still flags them as errors when they're in the `year` field though. I think a warning would be more appropriate than an error.

**Comment by johanneswilm** [comment] 2016-11-24 08:57
It should only flag them if it cannot interpret them. If it does understand the syntax, it should just process it.

**Comment by retorquere** [comment] 2016-11-24 08:57
Sure, yes.

**Comment by johanneswilm** [comment] 2016-11-24 14:20
with the error message resolved, the remaining part of this issue seems to be a duplicate of #13.

**Closed by johanneswilm** 2016-11-24 14:20 UTC
