### ISSUE TITLE
Part of title interpreted as variable?

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#52] opened 2017-08-22 22:16 UTC
When I run this script:

```
var BibTeXParser, data, fs, parseReferences;

BibTeXParser = require('biblatex-csl-converter').BibLatexParser;

parseReferences = function(input) {
  var parser, references;
  parser = new BibTeXParser(input, {
    rawFields: true,
    processUnexpected: true,
    processUnknown: true
  });

  references = parser.output;

  return {
    references: references,
    groups: parser.groups,
    errors: parser.errors,
    warnings: parser.warnings
  };
};

data = `
@InProceedings{test_citation1,
  Title                    = {{T}est {T}itle {W}ith 100~$\mu\${J}, 200\,{\mbox{$\mu$}}{J} {E}nergy, and $\pm$0.1\% {A}ccuracy, 0.2\,mm$^2$ {S}ize, and $-$50\,d{B} {A}ttenuation},
}
`

console.log(JSON.stringify(parseReferences(data), null, 2));
```

the last part of the title comes out as 

```
{
            "type": "variable",
            "attrs": {
              "variable": " {A}ccuracy, 0.2,mm$^2$ {S}ize, and $-$50,d{B} {A}ttenuation"
            }
          }
```

**Comment by johanneswilm** [comment] 2017-08-23 13:21
Copying the bibtex string and pasting it here: https://fiduswriter.github.io/biblatex-csl-converter/ I cannot reproduce the issue. It seems to be processed correctly.

**Comment by retorquere** [comment] 2017-08-23 13:30
Even when I run my script with the settings in that page, I still get `variable`. What do you get when you run that script in node?

**Comment by johanneswilm** [comment] 2017-08-23 13:33
I will try to set that up. Does it work for you if you paste it on the site though?

**Comment by retorquere** [comment] 2017-08-23 13:33
(I've attached the full output I get when running the script. I'm on biblatex-csl-converter@0.21.8

**Comment by retorquere** [comment] 2017-08-23 13:33
Works for me if I paste it into the site.

**Comment by retorquere** [comment] 2017-08-23 13:36
setup should be covered with going into an empty directory, running `npm init` (all defaults are OK), running `npm install biblatex-csl-converter`, and then running my script in that directory.

**Comment by johanneswilm** [comment] 2017-08-23 13:37
Before I start going through setting up node, etc. -- You are aware that you are inserting the bibtex code as a template literal which probably means that the escaping backslashes are removed by JS before it is being given to the parser, right?

**Comment by johanneswilm** [comment] 2017-08-23 13:39
For example this `${J}` -- has a meaning in template literals. it basically makes you refer to a variable called "J"

**Comment by retorquere** [comment] 2017-08-23 13:42
That was it 😊

**Comment by johanneswilm** [comment] 2017-08-23 13:42
:) Ok, so we can close this?

**Closed** 2017-08-23 13:42 UTC
