### ISSUE TITLE
"collaborator" field is not parsed

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#10] opened 2016-11-23 15:22 UTC
```
@incollection{robinson2007theoriesglobalization,
  title = {{Theories of globalization}},
  booktitle = {{The Blackwell companion to globalization}},
  publisher = {{John Wiley \& Sons}},
  author = {Robinson, William I},
  collaborator = {Ritzer, George},
  year = {2007},
  keywords = {orphaned},
  pages = {125-143},
  annote = {Extracted Annotations (zondag 17 november 2013 15:45:35) "What is the relationship between globalization and the nation-state? Is the nation-state being undermined?" (Robinson 2007:127) Relatedly, to what extent is the relationship between social structure and territoriality being redefined by globalization? Is there a deterritorialization of social relations under globalization? What is the relationship between the local and the global? How are space and time being reconfigured? (note on p.127) "Relatedly, to what extent is the relationship between social structure and territoriality being redefined by globalization? Is there a deterritorialization of social" (Robinson 2007:127) "relations under globalization? What is the relationship between the local and the global? How are space and time being reconfigured?" (Robinson 2007:128) "THE NETWORK SOCIETY Manuel Castells' groundbreaking trilogy, The Rise of the Network Society (1996, 1997, 1998), exemplifies a 'technologistic' approach to globalization" (Robinson 2007:132) "'communication decisively shapes culture because we do not see . . . reality as it 'is' but as our languages are'. He adds, 'we are not living in a global village, but in customized cottages, globally produced and locally distributed' (1996: 370)." (Robinson 2007:133)},
  file = {Robinson_2007_Theories of globalization.pdf:Better BibTeX.015/F64PVIN4/Robinson_2007_Theories of globalization.pdf:application/pdf}
}
```

**Comment by johanneswilm** [comment] 2016-11-23 17:39
duplicate of #11

**Closed by johanneswilm** 2016-11-23 17:39 UTC
