### ISSUE TITLE
\enquote is not parsed

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#9] opened 2016-11-23 15:17 UTC
```
@article{1e, author = "01e",  title = {Blah  \emph{emph} and \enquote{enquote}.},}
```

parses to

```
title: 'Blah <i>emph</i> and qnquote<span class="nocase">enquote</span>.'
```

**Comment by johanneswilm** [comment] 2016-11-23 17:03
Hmm, I cannot reproduce this here. in CSL I get:

```
title:	"Blah <span class="nocase"><i>emph</i></span> and <span class="nocase">&ldquo;enquote&rdquo;</span>."
```

In biblatex export I get

```
title = {Blah {{\mkbibitalic{emph}}} {and} {{\enquote{enquote}}}.} 
```

Maybe this has been fixed in one of the recent commits?

**Comment by retorquere** [comment] 2016-11-23 17:13
Looks like it.

**Closed** 2016-11-23 17:14 UTC
